services:
  - type: web
    name: mabini-skyview
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn mabini_skyview.wsgi:application
    autoDeploy: true