services:
  - type: web
    name: mabini-skyview
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py makemigrations && python manage.py migrate && python manage.py seed_data && python manage.py collectstatic --noinput 
    startCommand: gunicorn mabini_skyview.wsgi:application
    autoDeploy: true